language: php
php:
  - 5.6
  - 7.0
before_script:
  - "pecl install mongodb"
  - "composer install"
script:
  - "vendor/bin/phpunit --exclude-group long spec"
  - "vendor/bin/phpunit --group long spec"
sudo: false
services: mongodb
